config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get '/import' => 'pages#import'
  
  match '/destroy', to: 'prospects#destroy', via: :delete

  resources :prospects do
      collection { post :import }
  end
  
  root to: "prospects#index"

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
    require 'csv'
    
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            
            prospect_hash = row.to_hash
            prospect = Prospect.where(id: prospect_hash["id"])

            if prospect.count == 1
                prospect.first.update_attributes(prospect_hash)
            else
                Prospect.create!(prospect_hash)
            end
        end
    end
end

app/models/website.rb
class Website < ActiveRecord::Base
    require 'csv'
    
    def self.import(file_website)
        CSV.foreach(file_website.path, headers: true) do |row|
            
            website_hash = row.to_hash
            website = Website.where(id: website_hash["id"])

            if website.count == 1
                website.first.update_attributes(website_hash)
            else
                Website.create!(website_hash)
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  def index
    @prospects = Prospect.all
  end

  def import
    Prospect.import(params[:file])
    redirect_to root_url, notice: "Prospects imported."
  end
  
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def index
    @websites = Website.all
  end

  def import
    Website.import(params[:file_website])
    redirect_to root_url, notice: "Prospects imported."
  end
  
  def destroy
    Prospect.destroy_all
    redirect_to root_url, notice: "Prospects deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LentzApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="css/simple-sidebar.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        LentzApp
                    </a>
                </li>
                <li>
                    <a href="/"><i class="fa fa-tachometer"></i>&nbsp; Dashboard</a>
                    <!--<%= link_to "Dashboard", root_path %>-->
                </li>
                <li>
                    <a href="/import"><i class="fa fa-upload"></i>&nbsp; Import</a>
                   <!-- <%= link_to "Import", import_path %>-->
                </li>
                <li>
                    <a href="#"><i class="fa fa-cog"></i>&nbsp; Settings</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-pencil-square-o"></i>&nbsp; Contact</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-inverse navbar-fixed-top">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <a href="#menu-toggle" class="btn btn-default navbar-brand" id="menu-toggle">
                                        <i class="fa fa-bars fa-1x"></i>
                                    </a>
                                </div>
                            </div>
                        </nav>
                        <div class="container-fluid">
                            <div id="flash">
                                <% flash.each do |key, value| %>
                                    <%= content_tag :div, value, class: "alert alert-#{key}" %>
                                <% end %>
                            </div>
                        </div>
                        <%= yield %>
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

    <script type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
        $('#flash').fadeOut();
      }, 3000);
    })
    </script>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/import.html.erb
<div class= "row">
  <div class= "container-fluid">
    <h3>Import a CSV File</h3>
    <div class="form-group">
      <%= form_tag import_prospects_path, multipart: true do %>
        <%= file_field_tag :file %></br>
        <%= submit_tag "Import CSV", class: "btn btn-primary" %>
      <% end %>
    </div>
    <h3>Website Checker</h3>
<!--    <div class="form-group">
      <%= form_tag import_prospects_path, multipart: true do %>
        <%= file_field_tag :file_website %></br>
        <%= submit_tag "Import CSV", class: "btn btn-primary" %>
      <% end %>
    </div>-->
  </div>
</div>

app/views/prospects/index.html.erb
<div class= "row">
  <div class= "container-fluid">
    <div class="btn-group" data-toggle="buttons">
      <label id= "green" class="btn btn-success">
        <input type="radio" name="options" id="option1" autocomplete="off"> Green
      </label>
      <label id= "yellow" class="btn btn-warning">
        <input type="radio" name="options" id="option2" autocomplete="off"> Yellow
      </label>
      <label id= "blue" class="btn btn-info">
        <input type="radio" name="options" id="option3" autocomplete="off"> Blue
      </label>
      <label id= "red" class="btn btn-danger">
        <input type="radio" name="options" id="option3" autocomplete="off"> Red
      </label>
    </div>
  </div>
</div>
<div class= "row">
  <% @companies = Prospect.all.group_by { |prospect| prospect.company } %>
  <% @companies.each do |key, value| %>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#<%= key.downcase.tr(" ", "_") %>" aria-expanded="true" aria-controls="<%= key %>">
            <%= key %>
          </a>
        </h4>
      </div>
      <div id="<%= key.downcase.tr(" ", "_") %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="<%= key.downcase.tr(" ", "_") %>">
          <div class="list-group">
            <table class="table table-hover table-bordered">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>LinkedIn</th>
                  <th>Company</th>
                </tr>
              </thead>
              <tbody>
                <% @companies[key].each do |prospect| %>
                  <tr>
                    <!--<td><%= prospect.id %></td>
                    <td><%= prospect.name %></td>
                    <td><%= prospect.email %></td>
                    <td><%= prospect.linkedin %></td>
                    <td><%= prospect.company %></td>-->
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class= "row"></br>
  <div class= "container-fluid">
    <%= link_to 'Delete all Records', destroy_path, method: :delete, class: "btn btn-danger" %>
  </div>
</div>

<script>
/*  $("tr").click(function() {
    if ($("#green").hasClass("active")) {
      $(this).removeClass.toggleClass("success");
    }
    if ($("#yellow").hasClass("active")) {
      $(this).removeClass.toggleClass("warning");
    }
  });*/
  $("tr").click(function() {
  $(this).removeClass();
  if ($("#green").hasClass("active")){
    $(this).addClass("success");
  }
  if ($("#yellow").hasClass("active")){
    $(this).addClass("warning");
  }
  if ($("#blue").hasClass("active")){
    $(this).addClass("info");
  }
  if ($("#red").hasClass("active")){
    $(this).addClass("danger");
  }
});
</script>